apiVersion: v1
kind: Namespace
metadata:
  creationTimestamp: null
  labels:
    api: test-certmanager
    kubebuilder.k8s.io: unknown
  name: test-certmanager-system
spec: {}
status: {}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  labels:
    api: test-certmanager
    kubebuilder.k8s.io: unknown
  name: test-certmanager-role
rules:
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - create
  - update
  - get
  - watch
  - list
- apiGroups:
  - admissionregistration.k8s.io
  resources:
  - mutatingwebhookconfigurations
  verbs:
  - get
  - watch
  - list
  - update
- apiGroups:
  - admissionregistration.k8s.io
  resources:
  - validatingwebhookconfigurations
  verbs:
  - get
  - watch
  - list
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  creationTimestamp: null
  labels:
    api: test-certmanager
    kubebuilder.k8s.io: unknown
  name: test-certmanager-rolebinding
  namespace: test-certmanager-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: test-certmanager-role
subjects:
- kind: ServiceAccount
  name: default
  namespace: test-certmanager-system
---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    api: test-certmanager
    control-plane: controller-manager
    kubebuilder.k8s.io: unknown
  name: test-certmanager-controller-manager-service
  namespace: test-certmanager-system
spec:
  clusterIP: None
  selector:
    api: test-certmanager
    control-plane: controller-manager
    kubebuilder.k8s.io: unknown
status:
  loadBalancer: {}
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  creationTimestamp: null
  labels:
    api: test-certmanager
    control-plane: controller-manager
    kubebuilder.k8s.io: unknown
  name: test-certmanager-controller-manager
  namespace: test-certmanager-system
spec:
  replicas: 1
  selector:
    matchLabels:
      api: test-certmanager
      control-plane: controller-manager
      kubebuilder.k8s.io: unknown
  serviceName: test-certmanager-controller-manager-service
  template:
    metadata:
      creationTimestamp: null
      labels:
        api: test-certmanager
        control-plane: controller-manager
        kubebuilder.k8s.io: unknown
    spec:
      containers:
      - args:
        - --install-crds=false
#        - -v=8
        - --alsologtostderr
        command:
        - /root/controller-manager
        image: gcr.io/mengqiy-dev/certmanager:v6
        imagePullPolicy: Always
        name: controller-manager
        resources:
          limits:
            cpu: 100m
            memory: 30Mi
          requests:
            cpu: 100m
            memory: 20Mi
      terminationGracePeriodSeconds: 10
  updateStrategy: {}
status:
  replicas: 0
